title: Knowing is power
description: I'm late but it's start
author: Jun's Dev Log
github: https://github.com/yujunkong
about: I'm Programmer for Java & C sharp. I've made on numerous projects
disqus_shortname: yjkong
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/yujun.kong.3"
    - icon: fa-github
      link: "https://github.com/yujunkong"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Useful Links
      url: /Projects/


url: "https://yujunkong.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
